# Generated by Django 5.2.8 on 2025-12-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0002_alter_prenotazione_itinerario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoarchivio',
            name='autore',
            field=models.CharField(choices=[('VERGA', 'Giovanni Verga'), ('CAPUANA', 'Luigi Capuana'), ('ALTRO', 'Altro/Generico')], default='ALTRO', help_text="Seleziona l'autore a cui appartiene questa foto.", max_length=20),
        ),
    ]
