# Generated by Django 5.2.8 on 2025-11-19 22:48

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0003_fotoarchivio_fotoarchiviotranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('immagine', models.ImageField(help_text="Immagine rappresentativa dell'itinerario.", upload_to='itinerari/')),
                ('distanza', models.DecimalField(decimal_places=2, help_text='Distanza in km (es: 35.14)', max_digits=6)),
                ('dislivello', models.IntegerField(help_text='Dislivello in metri (es: 1199)')),
                ('tempo_stimato', models.CharField(help_text="Tempo stimato (es: '1:27:18' o '1 ora e 30 minuti')", max_length=50)),
                ('link_mappa', models.URLField(help_text='Link alla mappa esterna (es: Google Maps, Komoot, etc.)', max_length=500)),
                ('ordine', models.IntegerField(default=0, help_text='Ordine di visualizzazione (numero più basso = prima).')),
                ('is_active', models.BooleanField(default=True, help_text="Se l'itinerario è attivo e visibile.")),
                ('tipo', models.CharField(choices=[('verghiano', 'Itinerario Verghiano'), ('capuaniano', 'Itinerario Capuaniano'), ('tematico', 'Itinerario Tematico')], default='verghiano', help_text='Tipo di itinerario.', max_length=50)),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerari',
                'ordering': ['ordine', 'translations__titolo'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItinerarioTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('titolo', models.CharField(help_text="Titolo dell'itinerario.", max_length=200)),
                ('descrizione', models.TextField(help_text="Descrizione dettagliata dell'itinerario.")),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parco_verismo.itinerario')),
            ],
            options={
                'verbose_name': 'Itinerario Translation',
                'db_table': 'parco_verismo_itinerario_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
