# Generated by Django 5.2.8 on 2025-11-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0004_itinerario_itinerariotranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='dislivello',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='distanza',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='tempo_stimato',
        ),
    ]
