# Generated by Django 5.2.8 on 2025-11-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0005_remove_itinerario_dislivello_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='link_mappa',
        ),
        migrations.AddField(
            model_name='itinerario',
            name='link_maps',
            field=models.URLField(blank=True, help_text='Link al percorso su Google Maps (opzionale)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='link_strava',
            field=models.URLField(blank=True, help_text='Link al percorso su Strava (opzionale)', max_length=500, null=True),
        ),
    ]
