# Generated by Django 5.2.8 on 2025-11-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0006_remove_itinerario_link_mappa_itinerario_link_maps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='link_maps',
        ),
    ]
