# Generated by Django on 2025-12-20 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parco_verismo", "0006_drop_legacy_prenotazione_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="richiesta",
            name="messaggio",
            field=models.TextField(
                blank=False,
                verbose_name="Messaggio/Richieste particolari",
                help_text="Inserisci il contenuto del messaggio (obbligatorio)",
            ),
        ),
        migrations.AlterField(
            model_name="richiesta",
            name="oggetto",
            field=models.CharField(
                max_length=200,
                blank=False,
                verbose_name="Oggetto",
                help_text="Oggetto della richiesta (obbligatorio)",
            ),
        ),
    ]
