# Generated by Django 5.2.8 on 2025-11-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0007_remove_itinerario_link_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='link_maps',
            field=models.URLField(blank=True, help_text='Link al percorso su Google Maps (opzionale)', max_length=500, null=True),
        ),
    ]
