# Generated by Django 5.2.8 on 2025-11-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0008_itinerario_link_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='link_strava',
        ),
    ]
