# Generated by Django 5.2.8 on 2025-11-20 18:45

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0009_remove_itinerario_link_strava'),
    ]

    operations = [
        migrations.CreateModel(
            name='TappaItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField(default=0, help_text="Ordine della tappa nell'itinerario (numero più basso = prima).")),
                ('immagine', models.ImageField(blank=True, help_text='Immagine rappresentativa della tappa (opzionale).', null=True, upload_to='tappe_itinerari/')),
                ('itinerario', models.ForeignKey(help_text='Itinerario a cui appartiene questa tappa.', on_delete=django.db.models.deletion.CASCADE, related_name='tappe', to='parco_verismo.itinerario')),
            ],
            options={
                'verbose_name': 'Tappa Itinerario',
                'verbose_name_plural': 'Tappe Itinerari',
                'ordering': ['ordine'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TappaItinerarioTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome', models.CharField(help_text="Nome della tappa (es. 'Tappa 1: Chiesa di Santa Margherita')", max_length=200)),
                ('descrizione', models.TextField(help_text='Descrizione dettagliata della tappa.')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parco_verismo.tappaitinerario')),
            ],
            options={
                'verbose_name': 'Tappa Itinerario Translation',
                'db_table': 'parco_verismo_tappaitinerario_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
