# Generated by Django 5.2.8 on 2026-01-14 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0012_eventodocumento_notiziadocumento'),
    ]

    operations = [
        # Elimina il modello TappaItinerario e le sue traduzioni
        migrations.DeleteModel(
            name='TappaItinerarioTranslation',
        ),
        migrations.DeleteModel(
            name='TappaItinerario',
        ),
        # Aggiungi nuovi campi a Itinerario
        migrations.AddField(
            model_name='itinerario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Modifica campo coordinate_tappe per avere default=list
        migrations.AlterField(
            model_name='itinerario',
            name='coordinate_tappe',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array JSON delle tappe: [{'nome': 'Nome tappa', 'coords': [lat, lng], 'descrizione': '...', 'order': 1}, ...]"
            ),
        ),
        # Modifica campo durata_stimata
        migrations.AlterField(
            model_name='itinerario',
            name='durata_stimata',
            field=models.CharField(max_length=100, blank=True, help_text="Es: '2-3 ore', 'Mezza giornata', 'Intera giornata'"),
        ),
        # Modifica campo immagine
        migrations.AlterField(
            model_name='itinerario',
            name='immagine',
            field=models.ImageField(upload_to='itinerari/', blank=True, null=True, help_text="Immagine di copertina dell'itinerario."),
        ),
        # Aggiungi campo note alle traduzioni
        migrations.AddField(
            model_name='itinerariotranslation',
            name='note',
            field=models.TextField(blank=True, help_text='Note aggiuntive, informazioni pratiche, consigli.'),
        ),
        # Aggiungi indici
        migrations.AddIndex(
            model_name='itinerario',
            index=models.Index(fields=['tipo', 'ordine'], name='parco_veris_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerario',
            index=models.Index(fields=['is_active'], name='parco_veris_is_active_idx'),
        ),
    ]
