# Generated by Django 5.2.8 on 2026-01-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0013_remove_tappa_itinerario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerario',
            options={'ordering': ['tipo', 'ordine'], 'verbose_name': 'Itinerario', 'verbose_name_plural': 'Itinerari'},
        ),
        migrations.RenameIndex(
            model_name='itinerario',
            new_name='parco_veris_tipo_12f4d4_idx',
            old_name='parco_veris_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='itinerario',
            new_name='parco_veris_is_acti_6256c4_idx',
            old_name='parco_veris_is_active_idx',
        ),
        migrations.AddField(
            model_name='itinerario',
            name='percorsi_calcolati',
            field=models.JSONField(blank=True, default=dict, help_text='Percorsi stradali pre-calcolati tra le tappe (generati automaticamente)'),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='colore_percorso',
            field=models.CharField(default='#FF5722', help_text='Colore del percorso sulla mappa (hex, es: #FF5722)', max_length=7),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='coordinate_tappe',
            field=models.JSONField(blank=True, default=list, help_text='Array JSON delle tappe: [{"nome": "Nome tappa", "coords": [lat, lng], "descrizione": "...", "order": 1}, ...]'),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='difficolta',
            field=models.CharField(choices=[('facile', 'Facile'), ('medio', 'Medio'), ('difficile', 'Difficile')], default='facile', help_text='Livello di difficoltà del percorso', max_length=20),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='icona_percorso',
            field=models.CharField(default='📍', help_text='Emoji o icona per il percorso (es: 📍, 📖, ⛪)', max_length=10),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Se deselezionato, l'itinerario non sarà visibile sul sito."),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='link_maps',
            field=models.URLField(blank=True, default='', help_text='Link al percorso su Google Maps (opzionale)', max_length=500),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='ordine',
            field=models.PositiveIntegerField(default=1, help_text='Ordine di visualizzazione (numero più basso = prima posizione).'),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='tipo',
            field=models.CharField(choices=[('verghiano', 'Itinerario Verghiano'), ('capuaniano', 'Itinerario Capuaniano'), ('tematico', 'Itinerario Tematico')], default='verghiano', help_text='Tipo di itinerario letterario.', max_length=50),
        ),
    ]
