# Generated by Django 5.2.8 on 2026-01-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0014_alter_itinerario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='galleria_immagini',
            field=models.JSONField(blank=True, default=list, help_text="Array di path delle immagini per il carosello: ['path/to/img1.jpg', 'path/to/img2.jpg']"),
        ),
    ]
