# Generated by Django 5.2.8 on 2026-01-15 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0015_itinerario_galleria_immagini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='galleria_immagini',
        ),
        migrations.CreateModel(
            name='ItinerarioImmagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(help_text="Carica un'immagine per la galleria dell'itinerario", upload_to='itinerari/galleria/', verbose_name='Immagine')),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione nel carosello', verbose_name='Ordine')),
                ('didascalia', models.CharField(blank=True, help_text="Descrizione dell'immagine (opzionale)", max_length=200, verbose_name='Didascalia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria', to='parco_verismo.itinerario', verbose_name='Itinerario')),
            ],
            options={
                'verbose_name': 'Immagine Galleria',
                'verbose_name_plural': 'Immagini Galleria',
                'ordering': ['ordine', 'created_at'],
            },
        ),
    ]
