# Generated by Django 5.2.8 on 2026-01-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0016_remove_itinerario_galleria_immagini_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='icona_percorso',
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='colore_percorso',
            field=models.CharField(default='#4A6741', help_text='Colore del percorso sulla mappa (hex, es: #4A6741)', max_length=7),
        ),
    ]
